import { createClient } from '@supabase/supabase-js';

// Supabase configuration
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('Supabase credentials not found. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env file');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Database types (will be auto-generated by Supabase CLI in production)
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          username: string;
          password: string | null;
          role_id: string | null;
          name: string;
        };
        Insert: {
          id?: string;
          username: string;
          password?: string | null;
          role_id?: string | null;
          name: string;
        };
        Update: {
          id?: string;
          username?: string;
          password?: string | null;
          role_id?: string | null;
          name?: string;
        };
      };
      // Add more table types as needed
    };
  };
};

