
export const currencies = [
    { code: 'AED', name: 'United Arab Emirates dirham' },
    { code: 'AFN', name: 'Afghan afghani' },
    { code: 'ALL', name: 'Albanian lek' },
    { code: 'AMD', name: 'Armenian dram' },
    { code: 'AOA', name: 'Angolan kwanza' },
    { code: 'ARS', name: 'Argentine peso' },
    { code: 'AUD', name: 'Australian dollar' },
    { code: 'AWG', name: 'Aruban florin' },
    { code: 'AZN', name: 'Azerbaijan Manat' },
    { code: 'BAM', name: 'Bosnia and Herzegovina convertible mark' },
    { code: 'BBD', name: 'Barbados dollar' },
    { code: 'BDT', name: 'Bangladeshi taka' },
    { code: 'BGN', name: 'Bulgarian lev' },
    { code: 'BHD', name: 'Bahraini dinar' },
    { code: 'BIF', name: 'Burundi franc' },
    { code: 'BMD', name: 'Bermudian dollar' },
    { code: 'BND', name: 'Brunei dollar' },
    { code: 'BOB', name: 'Bolivian boliviano' },
    { code: 'BRL', name: 'Brazilian real' },
    { code: 'BSD', name: 'Bahamian dollar' },
    { code: 'BTN', name: 'Bhutanese ngultrum' },
    { code: 'BWP', name: 'Botswana pula' },
    { code: 'BYN', name: 'Belarussian rouble' },
    { code: 'BZD', name: 'Belize dollar' },
    { code: 'CAD', name: 'Canadian dollar' },
    { code: 'CDF', name: 'Congolese franc' },
    { code: 'CHF', name: 'Swiss franc' },
    { code: 'CLP', name: 'Chilean peso' },
    { code: 'CNY', name: 'Chinese Yuan Renminbi' },
    { code: 'COP', name: 'Colombian peso' },
    { code: 'CRC', name: 'Costa Rican colón' },
    { code: 'CUP', name: 'Cuban peso' },
    { code: 'CVE', name: 'Cape Verde escudo' },
    { code: 'CZK', name: 'Czech koruna' },
    { code: 'DJF', name: 'Djibouti franc' },
    { code: 'DKK', name: 'Danish krone' },
    { code: 'DOP', name: 'Dominican peso' },
    { code: 'DZD', name: 'Algerian dinar' },
    { code: 'EGP', name: 'Egyptian pound' },
    { code: 'ERN', name: 'Eritrean nakfa' },
    { code: 'ETB', name: 'Ethiopian birr' },
    { code: 'EUR', name: 'Euro' },
    { code: 'FJD', name: 'Fiji dollar' },
    { code: 'FKP', name: 'Falkland Islands pound' },
    { code: 'GBP', name: 'Pound sterling' },
    { code: 'GEL', name: 'Georgian lari' },
    { code: 'GHS', name: 'Ghana cedi' },
    { code: 'GIP', name: 'Gibraltar pound' },
    { code: 'GMD', name: 'Gambian dalasi' },
    { code: 'GNF', name: 'Guinean franc' },
    { code: 'GTQ', name: 'Guatemalan quetzal' },
    { code: 'GYD', name: 'Guyana dollar' },
    { code: 'HKD', name: 'Hong Kong dollar' },
    { code: 'HNL', name: 'Honduran lempira' },
    { code: 'HTG', name: 'Haitian gourde' },
    { code: 'HUF', name: 'Hungarian forint' },
    { code: 'IDR', name: 'Indonesian rupiah' },
    { code: 'ILS', name: 'New Israeli shekel' },
    { code: 'INR', name: 'Indian rupee' },
    { code: 'IQD', name: 'Iraqi dinar' },
    { code: 'IRR', name: 'Iranian rial' },
    { code: 'ISK', name: 'Iceland króna' },
    { code: 'JMD', name: 'Jamaican dollar' },
    { code: 'JOD', name: 'Jordanian dinar' },
    { code: 'JPY', name: 'Japanese yen' },
    { code: 'KES', name: 'Kenyan shilling' },
    { code: 'KGS', name: 'Kyrgyzstani som' },
    { code: 'KHR', name: 'Cambodian riel' },
    { code: 'KMF', name: 'Comorian franc' },
    { code: 'KRW', name: 'South Korean won' },
    { code: 'KWD', name: 'Kuwaiti dinar' },
    { code: 'KYD', name: 'Cayman Islands dollar' },
    { code: 'KZT', name: 'Kazakhstani tenge' },
    { code: 'LAK', name: 'Lao kip' },
    { code: 'LBP', name: 'Lebanese pound' },
    { code: 'LKR', name: 'Sri Lankan rupee' },
    { code: 'LRD', name: 'Liberian dollar' },
    { code: 'LSL', name: 'Lesotho loti' },
    { code: 'LYD', name: 'Libyan dinar' },
    { code: 'MAD', name: 'Moroccan dirham' },
    { code: 'MDL', name: 'Moldovan leu' },
    { code: 'MGA', name: 'Malagasy ariary' },
    { code: 'MKD', name: 'Macedonian denar' },
    { code: 'MMK', name: 'Myanmar Kyat' },
    { code: 'MNT', name: 'Mongolian Tugrik' },
    { code: 'MOP', name: 'Macanese pataca' },
    { code: 'MRU', name: 'Mauritanian ouguiya' },
    { code: 'MUR', name: 'Mauritian rupee' },
    { code: 'MVR', name: 'Maldivian rufiyaa' },
    { code: 'MWK', name: 'Malawi kwacha' },
    { code: 'MXN', name: 'Mexican peso' },
    { code: 'MYR', name: 'Malaysian ringgit' },
    { code: 'MZN', name: 'Mozambique Metical' },
    { code: 'NAD', name: 'Namibian dollar' },
    { code: 'NGN', name: 'Nigerian naira' },
    { code: 'NIO', name: 'Nicaraguan córdoba' },
    { code: 'NOK', name: 'Norwegian krone' },
    { code: 'NPR', name: 'Nepalese rupee' },
    { code: 'NZD', name: 'New Zealand dollar' },
    { code: 'OMR', name: 'Omani rial' },
    { code: 'PAB', name: 'Panamanian balboa' },
    { code: 'PEN', name: 'Peruvian sol' },
    { code: 'PGK', name: 'Papua New Guinean kina' },
    { code: 'PHP', name: 'Philippine piso' },
    { code: 'PKR', name: 'Pakistan rupee' },
    { code: 'PLN', name: 'Polish zloty' },
    { code: 'PYG', name: 'Paraguayan guaraní' },
    { code: 'QAR', name: 'Qatari riyal' },
    { code: 'RON', name: 'Romanian Leu' },
    { code: 'RSD', name: 'Serbian Dinar' },
    { code: 'RUB', name: 'Russian ruble' },
    { code: 'RWF', name: 'Rwandan franc' },
    { code: 'SAR', name: 'Saudi riyal' },
    { code: 'SBD', name: 'Solomon Islands dollar' },
    { code: 'SCR', name: 'Seychellois rupee' },
    { code: 'SDG', name: 'Sudanese Pound' },
    { code: 'SEK', name: 'Swedish krona' },
    { code: 'SGD', name: 'Singapore dollar' },
    { code: 'SHP', name: 'Saint Helena pound' },
    { code: 'SLE', name: 'Sierra Leonean leone' },
    { code: 'SOS', name: 'Somali shilling' },
    { code: 'SRD', name: 'Surinam dollar' },
    { code: 'SSP', name: 'South Sudanese pound' },
    { code: 'STN', name: 'São Tomé and Príncipe dobra' },
    { code: 'SYP', name: 'Syrian pound' },
    { code: 'SZL', name: 'Swazi lilangeni' },
    { code: 'THB', name: 'Thai baht' },
    { code: 'TJS', name: 'Tajikistani somoni' },
    { code: 'TMT', name: 'Turkmenistan manat' },
    { code: 'TND', name: 'Tunisian dinar' },
    { code: 'TOP', name: 'Tongan paʻanga' },
    { code: 'TRY', name: 'Turkish lira' },
    { code: 'TTD', name: 'Trinidad and Tobago dollar' },
    { code: 'TWD', name: 'New Taiwan dollar' },
    { code: 'TZS', name: 'Tanzanian shilling' },
    { code: 'UAH', name: 'Ukrainian hryvnia' },
    { code: 'UGX', name: 'Ugandan shilling' },
    { code: 'USD', name: 'United States dollar' },
    { code: 'UYU', name: 'Uruguayan peso' },
    { code: 'UZS', name: 'Uzbekistan sum' },
    { code: 'VES', name: 'Venezuelan bolivar soberano' },
    { code: 'VND', name: 'Vietnamese dong' },
    { code: 'VUV', name: 'Vanuatu vatu' },
    { code: 'WST', name: 'Samoan tala' },
    { code: 'XAF', name: 'Central African CFA franc' },
    { code: 'XCD', name: 'East Caribbean dollar' },
    { code: 'XCG', name: 'Caribbean Guilder' },
    { code: 'XOF', name: 'West African CFA franc' },
    { code: 'XPF', name: 'CFP franc' },
    { code: 'YER', name: 'Yemeni rial' },
    { code: 'ZAR', name: 'South African rand' },
    { code: 'ZIG', name: 'Zimbabwean gold' },
    { code: 'ZMW', name: 'Zambian Kwacha' },
];
